project_name: remnawave-telegram-shop-bot
builds:
  - main: ./cmd/bot
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w -X main.Version={{.Version}}
    flags: ["-trimpath", "-buildvcs=false"]
release:
  github:
    owner: Jolymmiels
    name: remnawave-telegram-shop
