services:
  db:
    image: postgres:17
    container_name: remnawave-telegram-shop-db
    hostname: remnawave-telegram-shop-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 5

  bot:
    # Собранный образ с GitHub Container Registry
    image: ghcr.io/jolymmiels/remnawave-telegram-shop-bot:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./translations:/translations:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${HEALTH_CHECK_PORT:-8080}/ > /dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3

  migrate:
    image: migrate/migrate:v4.17.2
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "$${DATABASE_URL}"
      - "up"
    volumes:
      - ./db/migrations:/migrations:ro
    profiles: ["migrate"]

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    profiles: ["debug"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
