package handler

const (
	CallbackBuy           = "buy"
	CallbackSell          = "sell"
	CallbackStart         = "start"
	CallbackConnect       = "connect"
	CallbackPayment       = "payment"
	CallbackBalance       = "balance"
	CallbackTopup         = "topup"
	CallbackTopupMethod   = "topup_method"
	CallbackPayFromBal    = "pay_balance"
	CallbackTrial         = "trial"
	CallbackActivateTrial = "activate_trial"
	CallbackReferral      = "referral"
	CallbackReferralStats = "referral_stats"
	CallbackPromoEnter    = "promo_enter"
	CallbackShareReferral = "share_referral"
	CallbackOther         = "other"
	CallbackFAQ           = "faq"
	CallbackTrafficLimit  = "traffic_limit"
	CallbackKeys          = "keys"
	CallbackQR            = "qr"
	CallbackShortLink     = "short_link"
	CallbackShortList     = "short_list"
	CallbackLocations     = "locations"
	CallbackRegenKey      = "regen_key"
	CallbackLanguage      = "language"
	CallbackSetLanguage   = "set_language"
)
