package handler

const (
	CallbackBuy                     = "buy"
	CallbackSell                    = "sell"
	CallbackStart                   = "start"
	CallbackConnect                 = "connect"
	CallbackPayment                 = "payment"
	CallbackBalance                 = "balance"
	CallbackTopup                   = "topup"
	CallbackTopupMethod             = "topup_method"
	CallbackPayFromBal              = "pay_balance"
	CallbackTrial                   = "trial"
	CallbackActivateTrial           = "activate_trial"
	CallbackReferral                = "referral"
	CallbackReferralStats           = "referral_stats"
	CallbackPromoCodes              = "promo_codes"
	CallbackPromoCreate             = "promo_create"
	CallbackPromoEnter              = "promo_enter"
	CallbackPromoList               = "promo_list"
	CallbackPromoFreeze             = "promo_freeze"
	CallbackPromoUnfreeze           = "promo_unfreeze"
	CallbackPromoConfirmationDelete = "promo_confirm_delete"
	CallbackPromoDelete             = "promo_delete"
	CallbackOther                   = "other"
	CallbackFAQ                     = "faq"
	CallbackTrafficLimit            = "traffic_limit"
	CallbackKeys                    = "keys"
	CallbackQR                      = "qr"
	CallbackShortLink               = "short_link"
	CallbackShortList               = "short_list"
	CallbackLocations               = "locations"
	CallbackRegenKey                = "regen_key"
	CallbackProxy                   = "proxy"
)
