name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --config=.golangci.yml --timeout=5m
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
      - name: Test build
        run: go build ./...
      - name: Unit tests
        run: go test ./tests -cover -coverpkg=./...
