name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.3
          args: --config=.golangci.yml --timeout=5m
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
      - name: Test build
        run: go build ./...
      - name: Unit tests
        run: go test ./...
